# Generated by Django 2.2.5 on 2020-07-14 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200707_0744'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_email_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='currency',
            field=models.CharField(blank=True, choices=[('USD', 'US dollor'), ('KRW', 'Korea Won')], default='KRW', max_length=3),
        ),
        migrations.AlterField(
            model_name='user',
            name='language',
            field=models.CharField(blank=True, choices=[('KR', 'Korean'), ('EN', 'English')], default='KR', max_length=2),
        ),
    ]
