# Generated by Django 2.2.5 on 2020-07-14 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200714_1335'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_email_confirmed',
        ),
        migrations.AddField(
            model_name='user',
            name='email_secret',
            field=models.CharField(default='', max_length=128),
        ),
    ]
