# Generated by Django 2.2.5 on 2020-07-15 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='login_method',
            field=models.CharField(choices=[('EM', 'Email'), ('GH', 'Github'), ('KK', 'Kakao')], default='EM', max_length=2),
        ),
    ]
