# Generated by Django 2.2.5 on 2020-06-29 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0007_auto_20200629_2107'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roomtype',
            options={'ordering': ['-created_at'], 'verbose_name': 'Room Type'},
        ),
    ]
