# Generated by Django 2.2.5 on 2020-06-29 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0008_auto_20200629_2112'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='roomtype',
            options={'ordering': ['-name'], 'verbose_name': 'Room Type'},
        ),
    ]
