# Generated by Django 2.2.5 on 2020-07-01 01:51

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rooms', '0010_auto_20200629_2129'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('peding', 'Pending'), ('confirmed', 'Confirmed'), ('canceled', 'Canceled')], default='peding', max_length=12)),
                ('checkin_date', models.DateField(default=datetime.datetime(2020, 7, 1, 1, 51, 14, 904161, tzinfo=utc), null=True)),
                ('checkout_date', models.DateField(default=datetime.datetime(2020, 7, 1, 1, 51, 14, 904191, tzinfo=utc), null=True)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.Room')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
