# Generated by Django 2.2.5 on 2020-07-01 02:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_auto_20200701_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='checkin_date',
            field=models.DateField(default=datetime.datetime(2020, 7, 1, 2, 23, 30, 879306, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='checkout_date',
            field=models.DateField(default=datetime.datetime(2020, 7, 1, 2, 23, 30, 879336, tzinfo=utc), null=True),
        ),
    ]
