# Generated by Django 2.2.5 on 2020-07-01 11:56

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_auto_20200701_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='checkin_date',
            field=models.DateField(default=datetime.datetime(2020, 7, 1, 11, 56, 55, 574926, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='checkout_date',
            field=models.DateField(default=datetime.datetime(2020, 7, 1, 11, 56, 55, 574960, tzinfo=utc), null=True),
        ),
    ]
